### ISSUE TITLE
Unlimited Liquid drums with Wireless Extra cells Liquid terminal - zC 0.0.13

### ISSUE THREAD

**Issue by FuzzyJem** [warezit/zitCraft#21] opened 2015-02-18 01:29 UTC
Set up liquid ME terminal and a wireless one. You can fill buckets, drums , or whatever can be filled wirelessly with it. When I insert one drum, in the left slot (input slot) and click which liquid i want to fill it with, the right slot (output slot) gives me a stack of 64 fully loaded of what ever liquid i want. I can then keep throwing the stack of 64 drums on the ground continuously giving me unlimited completely full drums of a liquid.

Edit: Doesnt seem to work with buckets or glass bottles. Trying bedrock drums next

**Comment by warezit** [comment] 2015-02-22 04:23
This "should" be fixed in zC 0.0.15

**Comment by warezit** [comment] 2015-02-23 05:17
Although I cannot reproduce this problem in zC 0.0.15, FuzzyJem says this is still a "thing".

**Comment by FuzzyJem** [comment] 2015-02-23 09:33
I was able to duplicate the same as before. Don't think this problem in particular was addressed in this update.

**Comment by warezit** [comment] 2015-04-10 02:11
Tested this glitch in zC 2.0 and it still exists. Removed ExtraCells 2 from zC 2.0 due to this dupe glitch.

**Closed as completed by warezit** 2015-04-10 02:11 UTC
