### ISSUE TITLE
Logon Crash -zC 0.0.21

### ISSUE THREAD

**Issue by Benjaminjex** [warezit/zitCraft#33] opened 2015-03-13 22:25 UTC
Log File: https://gist.github.com/Benjaminjex/ad12c18620c656db3241

I log onto the server, see the view I should have, see myself poisoned/withered, hear myself die, and then crash back to launcher.

**Comment by warezit** [comment] 2015-03-13 23:43
Hmm.

Well... The first issue is that this crash log is from 5 months ago, and not for zitCraft.

Can you recheck your log folder, and grab your most recent file?

It should be in: (~ means wherever you have the Technic Launcher installed)
`~/technic/logs/`
or:
`~/technic/modpacks/zitcraft/logs/`
OR:
`~/technic/modpacks/zitcraft/crash-reports/`

**Comment by Benjaminjex** [comment] 2015-03-14 00:00
×Faccepalm×
Lemme get the right file

**Comment by Benjaminjex** [comment] 2015-03-14 00:20
https://gist.github.com/Benjaminjex/81b034d0f71cc999c4ff

**Comment by warezit** [comment] 2015-03-14 00:21
Yikes. Now that log file is even too big for Gist.

Sorry for the headache. Could you put the log file onto DropBox? or, something similar?

**Comment by warezit** [comment] 2015-03-14 00:22
Nevermind - I got it working. Give me a min to look at it.

**Comment by warezit** [comment] 2015-03-14 00:31
Looks like the crash is being caused by a potion effect.

I have seen this problem once before. It was caused by being too close to a certain type of entity. I just looked into your player's .dat file, and it looks like you are in the Nether, and most likely having the same problem as I saw before.

Can you look @ DynMap and tell me the coords of your base? I'll move you back there...

**Comment by Benjaminjex** [comment] 2015-03-14 00:34
Yea, -1832, 548. It is one of those floating dungeons.

**Comment by warezit** [comment] 2015-03-14 00:36
Okay, your player's file should be fixed so you are back @ your base. Try to connect now, and see if that works. I'll try to hunt down what is causing this "potion effect" error...

**Comment by Benjaminjex** [comment] 2015-03-14 00:39
gotcha. By the way ware, you really don't need to worry about causing people headaches. You devote a lot of time and effort into this thing, responding almost instantly all the time. On top of that this is a BIG modded thing going on, it is a given there will be problems. A small price to pay for the enjoyment it brings us.

**Comment by Benjaminjex** [comment] 2015-03-14 00:45
Its working!

**Comment by warezit** [comment] 2015-03-14 01:19
Jex, Thank you very much for those kind words!

Also, yes, there will always be at least one or two problems with running modded MC. But, I like the challenge, and I am happy to have community members like yourself around who respect everyone else and the dev process.

Also, Great to hear that fixed the problem (for now). This will at least give me a little time to investigate the issue more. Cheers!

**Closed as completed by warezit** 2015-03-14 01:19 UTC
